const PROGRAM={
Monday:{title:'Lower Body Strength',focus:'Legs • hills • pack carrying',duration:30,exercises:[
{name:'Warm-up',prescription:'5 min',type:'time',rest:0,notes:'Bodyweight squat, hip hinge, reverse lunge, calf raise, marching.'},
{name:'Goblet Squat',prescription:'3 × 8–12',sets:3,min:8,max:12,rest:60},
{name:'DB Romanian Deadlift',prescription:'3 × 8–12',sets:3,min:8,max:12,rest:60},
{name:'Reverse Lunge',prescription:'2 × 8/leg',sets:2,min:8,max:8,rest:45},
{name:'Standing Calf Raise',prescription:'2 × 15–20',sets:2,min:15,max:20,rest:45},
{name:'Farmer Carry',prescription:'7 × 40 sec',sets:7,type:'time',seconds:40,rest:20}]},
Tuesday:{title:'Archery Upper Body',focus:'Back • shoulders • core',duration:30,exercises:[
{name:'Shoulder Prep',prescription:'5 min',type:'time',rest:0,notes:'Arm circles, scapular push-ups, shoulder blade squeezes, light rows.'},
{name:'1-Arm DB Row',prescription:'3 × 10/side',sets:3,min:10,max:10,rest:60},
{name:'DB Floor Press',prescription:'3 × 8–12',sets:3,min:8,max:12,rest:60},
{name:'Bent-Over Rear-Delt Raise',prescription:'3 × 12–15',sets:3,min:12,max:15,rest:45},
{name:'Hammer Curl',prescription:'2 × 10–12',sets:2,min:10,max:12,rest:45},
{name:'Suitcase Carry',prescription:'4 rounds × 40 sec/side',sets:8,type:'time',seconds:40,rest:20}]},
Wednesday:{title:'Ruck Day',focus:'Hunting-specific conditioning',duration:30,exercises:[
{name:'Weighted Walk / Ruck',prescription:'30 min',type:'ruck',rest:0,notes:'Start with 10–15 lb. Brisk pace. No running. Add ~5 lb every 1–2 weeks until 25–30 lb is comfortable.'}]},
Thursday:{title:'Full-Body Strength',focus:'Strength • stability • durability',duration:30,exercises:[
{name:'Dynamic Warm-up',prescription:'5 min',type:'time',rest:0},
{name:'Goblet Squat',prescription:'3 rounds × 10',sets:3,min:10,max:10,rest:0},
{name:'1-Arm DB Row',prescription:'3 rounds × 10/side',sets:3,min:10,max:10,rest:0},
{name:'DB Floor Press',prescription:'3 rounds × 10',sets:3,min:10,max:10,rest:0},
{name:'DB Romanian Deadlift',prescription:'3 rounds × 10',sets:3,min:10,max:10,rest:0},
{name:'Step-Up',prescription:'3 rounds × 8/leg',sets:3,min:8,max:8,rest:75},
{name:'Plank',prescription:'5 min block',type:'time',seconds:45,rest:30}]},
Friday:{title:'Hunter Conditioning',focus:'Work capacity • controlled intensity',duration:30,exercises:[
{name:'Warm-up',prescription:'5 min',type:'time',rest:0},
{name:'20-Min Hunter Circuit',prescription:'AMRAP quality rounds',type:'circuit',rest:0,notes:'8 goblet squats • 8 push-ups • 10 DB RDLs • 8 reverse lunges/leg • 10 one-arm rows/side • 30-sec farmer carry. Do not race.'},
{name:'Easy Walk / Cooldown',prescription:'5 min',type:'time',rest:0}]},
Saturday:{title:'Easy Outdoor Day',focus:'Ruck base • mobility',duration:30,exercises:[
{name:'Easy Weighted Walk',prescription:'20–25 min',type:'ruck',rest:0,notes:'Use 10–15 lb initially.'},
{name:'Mobility',prescription:'5–10 min',type:'time',rest:0,notes:'Calves, ankles, hips, hamstrings, thoracic rotation, shoulders/chest.'}]},
Sunday:{title:'Recovery',focus:'Rest • family • easy movement',duration:0,exercises:[
{name:'No structured training',prescription:'Recover',type:'rest',rest:0,notes:'Easy walking is fine. Recovery counts.'}]}}
const BENCHMARKS=[
{id:'goblet',label:'Goblet squat',target:52.5,unit:'lb × 12'},
{id:'rdl',label:'DB Romanian deadlift',target:105,unit:'lb total × 10–12'},
{id:'row',label:'1-arm DB row',target:45,unit:'lb × 10'},
{id:'carry',label:'Farmer carry',target:105,unit:'lb total × 60 sec'},
{id:'pushup',label:'Push-ups',target:20,unit:'clean reps'},
{id:'plank',label:'Plank',target:90,unit:'seconds'},
{id:'ruck',label:'Ruck',target:30,unit:'lb for 30 min'}]
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)]
function getState(){return{startDate:localStorage.hr30_startDate||new Date().toISOString().slice(0,10),history:JSON.parse(localStorage.hr30_history||'[]'),benchmarks:JSON.parse(localStorage.hr30_benchmarks||'{}'),bodyWeight:localStorage.hr30_bodyWeight||'',waist:localStorage.hr30_waist||'',preferredRuck:Number(localStorage.hr30_preferredRuck||10)}}
if(!localStorage.hr30_startDate)localStorage.hr30_startDate=new Date().toISOString().slice(0,10)
function saveHistory(item){const s=getState();s.history.unshift(item);localStorage.hr30_history=JSON.stringify(s.history.slice(0,100))}
function dayName(d=new Date()){return d.toLocaleDateString('en-US',{weekday:'long'})}
function formatDate(d=new Date()){return d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function weekNumber(){const start=new Date(localStorage.hr30_startDate+'T00:00:00'),now=new Date(),diff=Math.max(0,now-start);return Math.min(8,Math.floor(diff/604800000)+1)}
function completedThisWeek(){const now=new Date(),first=new Date(now),day=(now.getDay()+6)%7;first.setDate(now.getDate()-day);first.setHours(0,0,0,0);return getState().history.filter(h=>new Date(h.date)>=first).length}
function tab(name){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='today')renderToday();if(name==='week')renderWeek();if(name==='progress')renderProgress();if(name==='history')renderHistory()}
$$('.nav-btn').forEach(b=>b.onclick=()=>tab(b.dataset.tab))
function exerciseList(workout){return workout.exercises.map((e,i)=>`<div class="exercise"><div class="exercise-num">${i+1}</div><div><h4>${e.name}</h4><p>${e.prescription}</p><div class="tag-row">${e.rest?`<span class="tag">${e.rest}s rest</span>`:''}${e.notes?`<span class="tag">${e.notes}</span>`:''}</div></div></div>`).join('')}
function renderToday(){const d=dayName(),w=PROGRAM[d],s=getState();$('#main').innerHTML=`<section class="card hero"><div class="kicker">Week ${weekNumber()} • ${d}</div><h2>${w.title}</h2><div class="sub">${w.focus}</div><div class="metrics"><div class="metric"><strong>${w.duration||'—'}</strong><span>minutes</span></div><div class="metric"><strong>${completedThisWeek()}</strong><span>sessions this week</span></div><div class="metric"><strong>${s.preferredRuck}</strong><span>lb ruck start</span></div></div>${w.duration?`<button class="primary" onclick="startWorkout('${d}')">START WORKOUT</button>`:`<button class="primary" onclick="quickLogRecovery()">LOG RECOVERY DAY</button>`}</section><div class="section-title"><h3>Today's plan</h3><small>${formatDate()}</small></div><section class="card">${exerciseList(w)}</section><section class="card"><div class="kicker">PHASE 1 RULE</div><h3>Leave 2–3 clean reps in reserve</h3><p class="sub">Weeks 1–2 are about consistency, not destruction. Once you hit the top of a rep range with clean form, add 2.5–5 lb next time.</p></section>`}
function renderWeek(){const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],today=dayName();$('#main').innerHTML=`<div class="section-title"><h3>8-week training week</h3><small>Week ${weekNumber()}</small></div><div class="day-grid">${days.map(d=>`<div class="day-card ${d===today?'today':''}"><div class="kicker">${d}</div><h4>${PROGRAM[d].title}</h4><p>${PROGRAM[d].focus}</p><button class="ghost" onclick="openDay('${d}')">View →</button></div>`).join('')}</div><section class="card" style="margin-top:14px"><div class="kicker">PROGRESSION</div><h3>Weeks 1–2</h3><p class="sub">Learn the movements. Stay conservative.</p><h3>Weeks 3–4</h3><p class="sub">Add reps or 2.5–5 lb whenever form stays clean.</p><h3>Weeks 5–8</h3><p class="sub">Push strength and bring ruck load gradually toward 20–30 lb.</p></section>`}
function openDay(d){openModal(`<div class="close-row"><div><div class="kicker">${d}</div><h2>${PROGRAM[d].title}</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><p class="sub">${PROGRAM[d].focus}</p><div class="card">${exerciseList(PROGRAM[d])}</div>${PROGRAM[d].duration?`<button class="primary" onclick="closeModal();startWorkout('${d}')">START THIS WORKOUT</button>`:''}`)}
function renderProgress(){const s=getState();$('#main').innerHTML=`<section class="card"><div class="kicker">HUNTER READINESS</div><h2 style="margin:6px 0">Benchmarks</h2><p class="sub">Update these as you train. The goal is capability, not a vanity score.</p>${BENCHMARKS.map(b=>{const val=Number(s.benchmarks[b.id]||0),pct=Math.min(100,Math.round((val/b.target)*100));return `<div class="benchmark"><div class="benchmark-top"><div><strong>${b.label}</strong><br><small>Goal: ${b.target} ${b.unit}</small></div><button class="ghost" onclick="editBenchmark('${b.id}')">${val||'Set'}</button></div><div class="progress-bar"><span style="width:${pct}%"></span></div></div>`}).join('')}</section><section class="card"><div class="kicker">BODY METRICS</div><div class="set-grid"><div class="field"><label>Body weight</label><input id="bw" inputmode="decimal" value="${s.bodyWeight}" placeholder="lb"></div><div class="field"><label>Waist</label><input id="waist" inputmode="decimal" value="${s.waist}" placeholder="in"></div></div><button class="primary" onclick="saveBody()">SAVE</button></section>`}
function editBenchmark(id){const b=BENCHMARKS.find(x=>x.id===id),s=getState(),old=s.benchmarks[id]||'';openModal(`<div class="close-row"><div><div class="kicker">UPDATE</div><h2>${b.label}</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>Current best (${b.unit})</label><input id="benchVal" inputmode="decimal" value="${old}"></div><button class="primary" onclick="saveBenchmark('${id}')">SAVE</button>`)}
function saveBenchmark(id){const s=getState();s.benchmarks[id]=Number($('#benchVal').value||0);localStorage.hr30_benchmarks=JSON.stringify(s.benchmarks);closeModal();renderProgress()}
function saveBody(){localStorage.hr30_bodyWeight=$('#bw').value;localStorage.hr30_waist=$('#waist').value;alert('Saved.')}
function renderHistory(){const h=getState().history;$('#main').innerHTML=`<div class="section-title"><h3>Workout history</h3><small>${h.length} logged</small></div><section class="card">${h.length?h.map(x=>`<div class="history-item"><div class="top"><div><h4>${x.day} — ${x.title}</h4><small>${new Date(x.date).toLocaleString()}</small></div><strong>${x.duration}m</strong></div>${x.summary?`<p class="note">${x.summary}</p>`:''}</div>`).join(''):`<div class="empty">Complete your first workout and it will show up here.</div>`}</section>`}
let active=null,interval=null,restInterval=null
function startWorkout(day){active={day,workout:PROGRAM[day],index:0,set:1,logs:[],started:Date.now(),remaining:PROGRAM[day].duration*60};openModal(workoutModal());clearInterval(interval);interval=setInterval(()=>{active.remaining=Math.max(0,active.remaining-1);const el=$('#workoutTimer');if(el)el.textContent=fmt(active.remaining)},1000)}
function fmt(sec){const m=Math.floor(sec/60),s=sec%60;return`${m}:${String(s).padStart(2,'0')}`}
function currentEx(){return active.workout.exercises[active.index]}
function workoutModal(){const e=currentEx(),sets=e.sets||1,weightDefault=lastWeight(e.name);return`<div class="workout-header"><div><div class="kicker">${active.day}</div><h2 style="margin:4px 0">${active.workout.title}</h2></div><div class="timer" id="workoutTimer">${fmt(active.remaining)}</div></div><div class="current-ex"><div class="kicker">EXERCISE ${active.index+1} OF ${active.workout.exercises.length}</div><h3>${e.name}</h3><p class="sub">${e.prescription}</p>${e.notes?`<p class="note">${e.notes}</p>`:''}${e.type==='ruck'?`<div class="set-grid"><div class="field"><label>Load (lb)</label><input id="weightInput" inputmode="decimal" value="${getState().preferredRuck}"></div><div class="field"><label>Minutes</label><input id="repsInput" inputmode="decimal" value="30"></div></div>`:(e.type==='time'||e.type==='circuit'||e.type==='rest')?`<div class="field"><label>Notes / rounds / result</label><input id="noteInput" placeholder="Optional"></div>`:`<div class="set-grid"><div class="field"><label>Weight (lb)</label><input id="weightInput" inputmode="decimal" value="${weightDefault||''}" placeholder="0"></div><div class="field"><label>Reps</label><input id="repsInput" inputmode="numeric" placeholder="${e.min||''}"></div></div><p class="note">Set ${active.set} of ${sets}</p>`}<div class="action-row"><button class="secondary" onclick="previousExercise()">BACK</button><button class="primary" style="margin-top:0" onclick="completeSet()">COMPLETE</button></div></div><button class="ghost" style="margin-top:16px" onclick="finishWorkout(true)">Finish early</button>`}
function lastWeight(name){for(const h of getState().history){if(h.logs){const found=[...h.logs].reverse().find(l=>l.name===name&&l.weight);if(found)return found.weight}}return''}
function completeSet(){const e=currentEx(),log={name:e.name,set:active.set};if($('#weightInput'))log.weight=Number($('#weightInput').value||0);if($('#repsInput'))log.reps=Number($('#repsInput').value||0);if($('#noteInput'))log.note=$('#noteInput').value;active.logs.push(log);if(e.sets&&active.set<e.sets){active.set++;if(e.rest)startRest(e.rest);else rerenderWorkout()}else{active.index++;active.set=1;if(active.index>=active.workout.exercises.length){finishWorkout(false);return}if(e.rest)startRest(e.rest);else rerenderWorkout()}}
function startRest(seconds){let left=seconds;$('#modal').innerHTML=`<div class="close-row"><div><div class="kicker">REST</div><h2>Recover, then go.</h2></div><button class="icon-btn" onclick="skipRest()">→</button></div><div class="rest-box"><div class="timer" id="restTimer">${fmt(left)}</div><p class="sub">Next: ${active.index<active.workout.exercises.length?currentEx().name:'Finish'}</p></div><button class="primary" onclick="skipRest()">SKIP REST</button>`;clearInterval(restInterval);restInterval=setInterval(()=>{left--;const el=$('#restTimer');if(el)el.textContent=fmt(Math.max(0,left));if(left<=0)skipRest()},1000)}
function skipRest(){clearInterval(restInterval);rerenderWorkout()}
function rerenderWorkout(){$('#modal').innerHTML=workoutModal()}
function previousExercise(){if(active.index>0){active.index--;active.set=1;rerenderWorkout()}}
function finishWorkout(early){clearInterval(interval);clearInterval(restInterval);const duration=Math.max(1,Math.round((Date.now()-active.started)/60000)),summary=progressionSummary(active.logs);saveHistory({date:new Date().toISOString(),day:active.day,title:active.workout.title,duration,logs:active.logs,summary});closeModal();active=null;tab('today');setTimeout(()=>alert(early?`Workout logged at ${duration} min.`:`Workout complete. ${summary||'Nice work.'}`),100)}
function progressionSummary(logs){const grouped={};logs.forEach(l=>{if(l.weight&&l.reps)(grouped[l.name]??=[]).push(l)});const recs=[];Object.entries(grouped).forEach(([name,arr])=>{const ex=Object.values(PROGRAM).flatMap(x=>x.exercises).find(e=>e.name===name);if(ex?.max&&arr.length>=ex.sets&&arr.every(x=>x.reps>=ex.max))recs.push(`${name}: consider +2.5–5 lb next time`)});return recs.join(' • ')}
function quickLogRecovery(){saveHistory({date:new Date().toISOString(),day:'Sunday',title:'Recovery',duration:0,summary:'Recovery day logged.'});renderToday()}
function openModal(html){$('#modal').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){clearInterval(restInterval);$('#modalBackdrop').classList.add('hidden')}
$('#modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()})
$('#settingsBtn').onclick=()=>{const s=getState();openModal(`<div class="close-row"><div><div class="kicker">SETTINGS</div><h2>HUNT READY 30</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="settings-grid"><div class="setting"><label>Program start date</label><input id="startDate" type="date" value="${s.startDate}"></div><div class="setting"><label>Starting ruck load (lb)</label><input id="ruckLoad" inputmode="numeric" value="${s.preferredRuck}"></div></div><button class="primary" onclick="saveSettings()">SAVE SETTINGS</button><p class="note">Your workout history stays on this device using local storage.</p><button class="secondary" style="width:100%;margin-top:10px" onclick="exportData()">EXPORT MY DATA</button>`)}
function saveSettings(){localStorage.hr30_startDate=$('#startDate').value||new Date().toISOString().slice(0,10);localStorage.hr30_preferredRuck=Number($('#ruckLoad').value||10);closeModal();renderToday()}
function exportData(){const s=getState(),data={exportedAt:new Date().toISOString(),...s};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hunt-ready-30-data.json';a.click();URL.revokeObjectURL(url)}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'))
renderToday()
